apiVersion: v1
kind: Service
metadata:
  name: frontend-sv1-svc
  labels:
    app: frontend-svc
spec:
  selector:
    app: frontend-one
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
