apiVersion: v1
kind: Service
metadata:
  name: backend-service-1
  labels:
    app: backend-1
spec:
  selector:
    app: backend-1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
