apiVersion: v1
kind: Service
metadata:
  name: backend-sv1-svc
  labels:
    app: backend-1-svc
spec:
  selector:
    app: backend-one
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
