apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-2-deployment
  namespace: devops
  labels:
    app: backend-two
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-two
  template:
    metadata:
      labels:
        app: backend-two
    spec:
      containers:
        - name: backend-two
          image: shafikur/backend-two:3.0
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: URL
              value: http://backend-sv1-svc.default.svc.cluster.local
