apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-2-deployment
  namespace: devops
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: shafikur/backend-two:3.0
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"