apiVersion: v1
kind: Service
metadata:
  name: backend-sv2-svc
  labels:
    app: backend-2
spec:
  selector:
    app: backend-two
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
