apiVersion: v1
kind: Service
metadata:
  name: backend-service-2
  labels:
    app: backend-2
spec:
  selector:
    app: backend-2
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
