apiVersion: v1
kind: Service
metadata:
  name: backend-sv2-svc
  namespace: devops
  labels:
    app: backend-1
spec:
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
